// vizarch — Export pipeline
// Produces JSON, Markdown, and PNG (browser-side) representations of a graph.
// SVG is produced by svg-builder.ts directly.

import type { ArchGraph } from "../types";
import { getProviderLabel, getTypeLabel } from "../services";
import { getGraphBounds } from "../layout-engine";

export function exportJson(graph: ArchGraph): string {
  return JSON.stringify(
    {
      version: 1,
      nodes: graph.nodes.map((n) => ({
        id: n.id,
        label: n.label,
        serviceId: n.serviceId,
        serviceName: n.serviceName,
        provider: n.provider,
        type: n.type,
        providerLabel: getProviderLabel(n.provider),
        typeLabel: getTypeLabel(n.type),
        description: n.description,
        docLink: n.docLink,
        x: n.x,
        y: n.y,
        layer: n.layer,
      })),
      edges: graph.edges.map((e) => ({
        id: e.id,
        from: e.from,
        to: e.to,
        protocol: e.protocol,
        label: e.label,
        style: e.style,
      })),
      bounds: getGraphBounds(graph),
      style: graph.style,
    },
    null,
    2,
  );
}

// ASCII-art / Markdown table export
export function exportMarkdown(graph: ArchGraph): string {
  const lines: string[] = [];
  lines.push(`# Architecture Diagram`);
  lines.push("");
  lines.push(`> Generated by **vizarch** — ${graph.nodes.length} nodes, ${graph.edges.length} edges`);
  lines.push("");

  lines.push("## Components");
  lines.push("");
  lines.push("| ID | Label | Service | Provider | Type |");
  lines.push("|----|-------|---------|----------|------|");
  for (const n of graph.nodes) {
    if (n.hidden) continue;
    lines.push(
      `| ${n.id} | ${n.label} | ${n.serviceName} | ${getProviderLabel(n.provider)} | ${getTypeLabel(n.type)} |`,
    );
  }
  lines.push("");

  lines.push("## Connections");
  lines.push("");
  lines.push("| From | To | Protocol | Label |");
  lines.push("|------|----|----------|-------|");
  for (const e of graph.edges) {
    if (e.hidden) continue;
    const fromNode = graph.nodes.find((n) => n.id === e.from);
    const toNode = graph.nodes.find((n) => n.id === e.to);
    lines.push(
      `| ${fromNode?.label ?? e.from} | ${toNode?.label ?? e.to} | ${e.protocol ?? "direct"} | ${e.label ?? ""} |`,
    );
  }
  lines.push("");

  // ASCII art layer layout
  lines.push("## ASCII Layout");
  lines.push("```");
  const nodeMap = new Map(graph.nodes.map((n) => [n.id, n]));
  const layers = new Map<number, typeof graph.nodes>();
  for (const n of graph.nodes) {
    if (n.hidden) continue;
    const l = n.layer ?? 0;
    if (!layers.has(l)) layers.set(l, []);
    layers.get(l)!.push(n);
  }
  const sortedLayers = Array.from(layers.keys()).sort((a, b) => a - b);
  for (const l of sortedLayers) {
    const ns = layers.get(l)!;
    const line = ns
      .map((n) => `[${n.label}]`)
      .join("  ─→  ");
    lines.push(`L${l}:  ${line}`);
    // Show outgoing edges
    const nextLayer = sortedLayers.find((x) => x > l);
    if (nextLayer === undefined) continue;
    const nextIds = new Set((layers.get(nextLayer) ?? []).map((n) => n.id));
    const cross = graph.edges.filter(
      (e) => nodeMap.get(e.from)?.layer === l && nextIds.has(e.to),
    );
    if (cross.length) {
      const labels = cross
        .map(
          (e) =>
            `${nodeMap.get(e.from)?.label} →${e.protocol ? `(${e.protocol})` : ""}→ ${nodeMap.get(e.to)?.label}`,
        )
        .join("   |   ");
      lines.push(`       ${labels}`);
    }
  }
  lines.push("```");
  lines.push("");
  return lines.join("\n");
}

// Browser-side PNG export from an SVG string.
// Uses an offscreen canvas + Image + Blob serialization.
export async function exportPngBrowser(
  svg: string,
  opts: { scale?: number } = {},
): Promise<Blob> {
  const scale = opts.scale ?? 2;
  const svgBlob = new Blob([svg], { type: "image/svg+xml;charset=utf-8" });
  const url = URL.createObjectURL(svgBlob);
  try {
    const img = await new Promise<HTMLImageElement>((resolve, reject) => {
      const img = new Image();
      img.crossOrigin = "anonymous";
      img.onload = () => resolve(img);
      img.onerror = (e) => reject(e);
      img.src = url;
    });
    const widthMatch = svg.match(/width="(\d+)"/);
    const heightMatch = svg.match(/height="(\d+)"/);
    const w = widthMatch ? parseInt(widthMatch[1], 10) : img.width || 800;
    const h = heightMatch ? parseInt(heightMatch[1], 10) : img.height || 600;
    const canvas = document.createElement("canvas");
    canvas.width = w * scale;
    canvas.height = h * scale;
    const ctx = canvas.getContext("2d");
    if (!ctx) throw new Error("Canvas 2D context unavailable");
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
    return new Promise((resolve, reject) => {
      canvas.toBlob(
        (blob) => (blob ? resolve(blob) : reject(new Error("toBlob failed"))),
        "image/png",
      );
    });
  } finally {
    URL.revokeObjectURL(url);
  }
}

export function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function downloadSvg(svg: string, filename = "architecture.svg") {
  const blob = new Blob([svg], { type: "image/svg+xml;charset=utf-8" });
  triggerDownload(blob, filename);
}

export function downloadText(text: string, filename: string, mime = "text/plain") {
  const blob = new Blob([text], { type: `${mime};charset=utf-8` });
  triggerDownload(blob, filename);
}

// Mermaid diagram export
export function exportMermaid(graph: ArchGraph): string {
  const lines: string[] = ["graph LR"];

  // Sanitize node labels for Mermaid
  function sanitize(s: string): string {
    return s.replace(/[^a-zA-Z0-9 _\-\/]/g, " ").trim().replace(/\s+/g, " ");
  }

  // Node shape mapping based on service type
  function nodeShape(n: ArchGraph["nodes"][0]): { prefix: string; suffix: string } {
    switch (n.type) {
      case "frontend":
      case "client":
        return { prefix: "[", suffix: "]" };        // rectangle
      case "database":
      case "cache":
        return { prefix: "((", suffix: "))" };       // cylinder
      case "queue":
        return { prefix: "{{", suffix: "}}" };       // hexagon
      case "cdn":
      case "networking":
        return { prefix: "{", suffix: "}" };         // rhombus
      case "monitoring":
      case "analytics":
        return { prefix: ">]", suffix: "]" };        // asymmetric
      case "security":
        return { prefix: "[/", suffix: "/]" };       // parallelogram
      default:
        return { prefix: "[", suffix: "]" };         // rectangle
    }
  }

  const nodeIdMap = new Map<string, string>();

  for (const n of graph.nodes) {
    if (n.hidden) continue;
    const shortId = `n${nodeIdMap.size + 1}`;
    nodeIdMap.set(n.id, shortId);
    const shape = nodeShape(n);
    lines.push(`  ${shortId}${shape.prefix}"${sanitize(n.label)} (${sanitize(n.serviceName)})"${shape.suffix}`);
  }

  lines.push("");

  for (const e of graph.edges) {
    if (e.hidden) continue;
    const fromId = nodeIdMap.get(e.from);
    const toId = nodeIdMap.get(e.to);
    if (!fromId || !toId) continue;
    const style = e.style === "dashed" ? "-.->" : e.style === "dotted" ? "~~~" : "-->";
    const label = e.label ? `|"${sanitize(e.label)}"|` : "";
    lines.push(`  ${fromId} ${style} ${label} ${toId}`);
  }

  return lines.join("\n");
}
