// POST /api/integrations/slack — Slack slash command endpoint
// Usage: /vizarch describe your system architecture
// Returns: ephemeral message with diagram link

import { NextRequest, NextResponse } from "next/server";
import { generateDiagram } from "@/lib/vizarch/diagram-service";
import { db } from "@/lib/db";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  const formData = await req.formData();
  const text = formData.get("text") as string;
  const responseUrl = formData.get("response_url") as string;
  const userName = formData.get("user_name") as string;

  if (!text || text.trim().length < 5) {
    return NextResponse.json({
      response_type: "ephemeral",
      text: "Usage: `/vizarch describe your system architecture` — e.g. `/vizarch React frontend on Vercel, Node.js API on Lambda, PostgreSQL on RDS`",
    });
  }

  try {
    // Generate the diagram
    const result = await generateDiagram({
      description: text.trim(),
      style: { layout: "horizontal", theme: "light" },
      useCache: true,
    });

    // Save to database for a shareable link
    const slug = Array.from({ length: 8 }, () =>
      Math.floor(Math.random() * 36).toString(36),
    ).join("");

    const diagram = await db.diagram.create({
      data: {
        slug,
        title: `Slack diagram by ${userName}`,
        description: text.trim().slice(0, 2000),
        graphJson: JSON.stringify(result.graph),
        styleJson: JSON.stringify(result.graph.style ?? {}),
        svgCache: result.svg,
      },
      select: { slug: true, id: true },
    });

    const origin = req.headers.get("origin") || `https://${req.headers.get("host") || "vizarch.app"}`;

    // Respond with link
    const response = {
      response_type: "in_channel",
      blocks: [
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `🏗️ *Architecture Diagram* — generated by ${userName}\n\n_${text.trim().slice(0, 100)}${text.length > 100 ? "…" : ""}_\n\n📊 <${origin}/?share=${diagram.slug}|View diagram> · ${result.meta.nodeCount} nodes · ${result.meta.edgeCount} edges`,
          },
        },
      ],
    };

    // Also send async to response_url if provided
    if (responseUrl) {
      fetch(responseUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(response),
      }).catch(() => {});
    }

    return NextResponse.json(response);
  } catch (err) {
    return NextResponse.json({
      response_type: "ephemeral",
      text: `Error generating diagram: ${(err as Error).message}`,
    });
  }
}

export async function GET() {
  return NextResponse.json({
    name: "vizarch Slack integration",
    description: "Use /vizarch slash command to generate architecture diagrams",
    usage: "POST to /api/integrations/slack with form-data: text=<description>",
  });
}
