// POST /api/integrations/slack — Slack slash command endpoint
// Usage: /vizarch describe your system architecture
// Returns: ephemeral message with diagram link
//
// Security: validates Slack request signature (v0) when SLACK_SIGNING_SECRET is set.

import { NextRequest, NextResponse } from "next/server";
import { generateDiagram } from "@/lib/vizarch/diagram-service";
import { db } from "@/lib/db";
import { createHmac, timingSafeEqual } from "crypto";

export const runtime = "nodejs";

const SLACK_SECRET = process.env.SLACK_SIGNING_SECRET;

async function verifySlackSignature(
  body: string,
  timestamp: string,
  signature: string,
): Promise<boolean> {
  if (!SLACK_SECRET) return true; // Skip if not configured (dev mode)
  if (!timestamp || !signature) return false;

  // Reject requests older than 5 minutes (replay protection)
  const age = Math.abs(Date.now() / 1000 - parseInt(timestamp, 10));
  if (age > 300) return false;

  const basestring = `v0:${timestamp}:${body}`;
  const hmac = createHmac("sha256", SLACK_SECRET).update(basestring).digest("hex");
  const expected = `v0=${hmac}`;
  try {
    return timingSafeEqual(Buffer.from(signature), Buffer.from(expected));
  } catch {
    return false;
  }
}

export async function POST(req: NextRequest) {
  // Verify Slack signature if configured
  const rawBody = await req.text();
  if (SLACK_SECRET) {
    const timestamp = req.headers.get("x-slack-request-timestamp") ?? "";
    const signature = req.headers.get("x-slack-signature") ?? "";
    if (!(await verifySlackSignature(rawBody, timestamp, signature))) {
      return NextResponse.json({ error: "Invalid signature" }, { status: 401 });
    }
  }

  const formData = await new Response(rawBody).formData();
  const text = formData.get("text") as string;
  const responseUrl = formData.get("response_url") as string;
  const userName = formData.get("user_name") as string;

  if (!text || text.trim().length < 5) {
    return NextResponse.json({
      response_type: "ephemeral",
      text: "Usage: `/vizarch describe your system architecture` — e.g. `/vizarch React frontend on Vercel, Node.js API on Lambda, PostgreSQL on RDS`",
    });
  }

  try {
    // Generate the diagram
    const result = await generateDiagram({
      description: text.trim(),
      style: { layout: "horizontal", theme: "light" },
      useCache: true,
    });

    // Save to database for a shareable link
    const slug = Array.from({ length: 8 }, () =>
      Math.floor(Math.random() * 36).toString(36),
    ).join("");

    const diagram = await db.diagram.create({
      data: {
        slug,
        title: `Slack diagram by ${userName}`,
        description: text.trim().slice(0, 2000),
        graphJson: JSON.stringify(result.graph),
        styleJson: JSON.stringify(result.graph.style ?? {}),
        svgCache: result.svg,
      },
      select: { slug: true, id: true },
    });

    const origin = req.headers.get("origin") || `https://${req.headers.get("host") || "vizarch.app"}`;

    // Respond with link
    const response = {
      response_type: "in_channel",
      blocks: [
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `🏗️ *Architecture Diagram* — generated by ${userName}\n\n_${text.trim().slice(0, 100)}${text.length > 100 ? "…" : ""}_\n\n📊 <${origin}/?share=${diagram.slug}|View diagram> · ${result.meta.nodeCount} nodes · ${result.meta.edgeCount} edges`,
          },
        },
      ],
    };

    // Also send async to response_url if provided
    if (responseUrl) {
      fetch(responseUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(response),
      }).catch(() => {});
    }

    return NextResponse.json(response);
  } catch (err) {
    return NextResponse.json({
      response_type: "ephemeral",
      text: `Error generating diagram: ${(err as Error).message}`,
    });
  }
}

export async function GET() {
  return NextResponse.json({
    name: "vizarch Slack integration",
    description: "Use /vizarch slash command to generate architecture diagrams",
    usage: "POST to /api/integrations/slack with form-data: text=<description>",
  });
}
